language: go

go:
  - 1.3
  - 1.4

install:
  - mkdir -p "$GOPATH/src/willnorris.com/go"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/willnorris.com/go/webmention"
  - go get -v -t -d willnorris.com/go/webmention/...

script:
  - go test -v willnorris.com/go/webmention/...
